const K="mycoin_demo_v3";let s=JSON.parse(localStorage.getItem(K)||"null")||{user:null,b:0,cash:0,p:1,last:1,f:false,h:[]};
const save=()=>localStorage.setItem(K,JSON.stringify(s));
const ru=n=>"₹"+Number(n).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
function createAccount(){let n=document.getElementById("name").value.trim();if(n.length<2)return alert("कम से कम 2 अक्षर का नाम डालें।");let x=n.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8)||"USER";s={user:{name:n,id:"MYC-"+x+"-"+Math.floor(1000+Math.random()*9000)},b:0,cash:0,p:1,last:1,f:false,h:[]};save();render()}
function logout(){if(!s.user)return;if(!confirm("Demo ID और उसका local data हटाना है?"))return;localStorage.removeItem(K);s={user:null,b:0,cash:0,p:1,last:1,f:false,h:[]};render()}
function add(icon,text){s.h.unshift({icon,text,t:new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})});s.h=s.h.slice(0,50)}
function faucet(){if(!s.user)return alert("पहले Demo ID बनाइए।");if(s.f)return msg("fmsg","Faucet पहले ही claim हो चुका है।",1);s.b+=1000;s.f=true;add("🎁","Received 1,000 MYC");save();render();msg("fmsg","1,000 Demo MYC मिल गए।")}
function move(){s.last=s.p;s.p=Math.max(.01,s.p*(1+(Math.random()*.30-.15)))}
function buy(){if(!s.user)return msg("tmsg","पहले Demo ID बनाइए।",1);let a=+document.getElementById("amount").value;if(!(a>0))return msg("tmsg","सही amount डालें।",1);let cost=a*s.p;if(s.cash<cost)return msg("tmsg","BUY करने के लिए virtual cash चाहिए। पहले MYC SELL करें।",1);s.cash-=cost;s.b+=a;move();add("🟢",`Bought ${a} MYC @ ${ru(s.last)}`);save();render();msg("tmsg",`BUY successful: ${a} MYC`)}
function sell(){if(!s.user)return msg("tmsg","पहले Demo ID बनाइए।",1);let a=+document.getElementById("amount").value;if(!(a>0))return msg("tmsg","सही amount डालें।",1);if(a>s.b)return msg("tmsg","इतना MYC balance में नहीं है।",1);let got=a*s.p;s.b-=a;s.cash+=got;move();add("🔴",`Sold ${a} MYC @ ${ru(s.last)}`);save();render();msg("tmsg",`SELL successful: ${a} MYC = ${ru(got)} virtual cash`)}
function clearHistory(){s.h=[];save();render()}
function msg(id,t,e){let x=document.getElementById(id);x.textContent=t;x.style.color=e?"#ff7585":"#55d59c";setTimeout(()=>x.textContent="",3000)}
function esc(x){return x.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){let a=document.getElementById("signup"),w=document.getElementById("walletbox");if(!s.user){a.classList.remove("hide");w.classList.add("hide")}else{a.classList.add("hide");w.classList.remove("hide");document.getElementById("uid").textContent=s.user.id;document.getElementById("bal").textContent=s.b.toLocaleString("en-IN")+" MYC";document.getElementById("price").textContent=ru(s.p);document.getElementById("cash").textContent=ru(s.cash);document.getElementById("tradeprice").textContent=ru(s.p);document.getElementById("change").textContent=((s.p-s.last)/s.last*100).toFixed(2)+"%"}document.getElementById("history").innerHTML=s.h.length?s.h.map(x=>`<li>${x.icon} ${esc(x.text)}<small>${x.t}</small></li>`).join(""):"<li>No transactions yet.</li>"}
document.addEventListener("DOMContentLoaded",render);